import { Camera, Check, Cigarette, Clock3, MapPin, PartyPopper, PawPrint, ShieldCheck, Star, UserRound, Volume2 } from "lucide-react";
import { AMENITY_LABELS } from "./housingDetail.constants";
import type { HousingDetails, RatingMetricItem } from "./housingDetail.types";
import { getGuestLabel, getReviewLabel, getRoomLabel, getRuleLabel } from "./housingDetail.utils";

interface Props { housing:HousingDetails; averageRating:number; reviewCount:number; ratingMetrics:RatingMetricItem[]; }
const HousingDetailsContent = ({housing,averageRating,reviewCount,ratingMetrics}:Props) => {
  const amenities=Array.isArray(housing.amenities)?housing.amenities:[];
  const safety=[
    housing.securityCameras&&{title:"Камери відеоспостереження",description:housing.securityCamerasDescription||"На території встановлені камери відеоспостереження.",icon:Camera},
    housing.noiseMonitor&&{title:"Датчик рівня шуму",description:housing.noiseMonitorDescription||"Пристрій контролює лише рівень гучності, без запису звуку.",icon:Volume2},
    housing.propertySafetyFeatures&&{title:"Охорона та особливості",description:housing.propertySafetyFeaturesDescription||"У помешканні передбачені додаткові заходи безпеки.",icon:ShieldCheck},
  ].filter(Boolean) as {title:string;description:string;icon:typeof Camera}[];
  return <div className="min-w-0">
    <div className="flex items-start gap-2 text-[16px] font-semibold text-[#202A31]"><MapPin size={18} className="mt-[2px] shrink-0 text-[#355872]"/><span>{[housing.address,housing.city].filter(Boolean).join(", ")}</span></div>
    <div className="mt-4 flex flex-wrap items-center gap-x-5 gap-y-2 border-b border-[#D8DDE0] pb-5 text-[12px] text-[#56636C]"><span>{housing.rooms} {getRoomLabel(housing.rooms)}</span><span>{housing.maxGuests} {getGuestLabel(housing.maxGuests)}</span>{typeof housing.bedrooms==="number"&&<span>{housing.bedrooms} спал.</span>}{typeof housing.beds==="number"&&<span>{housing.beds} ліж.</span>}{averageRating>0&&<span className="flex items-center gap-1 font-medium text-[#202A31]"><Star size={14} fill="#FFB341" stroke="#FFB341"/>{averageRating.toFixed(1)}{reviewCount>0&&<span className="ml-2 font-normal text-[#56636C]">{reviewCount} {getReviewLabel(reviewCount)}</span>}</span>}</div>
    {ratingMetrics.length>0&&<section className="grid grid-cols-1 gap-x-5 gap-y-3 border-b border-[#D8DDE0] py-5 sm:grid-cols-2 lg:grid-cols-3">{ratingMetrics.map(x=><RatingMetric key={x.label} {...x}/>)}</section>}
    {housing.description&&<section className="border-b border-[#D8DDE0] py-7"><p className="whitespace-pre-line text-[14px] leading-[1.55] text-[#252E34]">{housing.description}</p></section>}
    {amenities.length>0&&<section className="border-b border-[#D8DDE0] py-7"><Title>Зручності</Title><div className="mt-4 grid grid-cols-1 gap-x-12 gap-y-3 sm:grid-cols-2">{amenities.map(a=><div key={a} className="flex items-center gap-2 text-[14px] text-[#252E34]"><Check size={17} strokeWidth={1.7}/><span>{AMENITY_LABELS[a]??a}</span></div>)}</div></section>}
    <section className="border-b border-[#D8DDE0] py-7"><Title>Правила дому</Title><div className="mt-5 space-y-4"><Rule icon={Clock3} title="Реєстрація заїзду:" value={housing.checkInTime||"Не вказано"}/><Rule icon={Clock3} title="Реєстрація виїзду:" value={housing.checkOutTime||"Не вказано"}/><Rule icon={Cigarette} title="Куріння та вейпінг:" value={getRuleLabel(housing.smokingRule)}/><Rule icon={PawPrint} title="Тварини:" value={getRuleLabel(housing.petsRule)}/>{housing.quietHoursMode==="enabled"&&<Rule icon={Volume2} title="Тихі години:" value={`${housing.quietHoursFrom||"22:00"} до ${housing.quietHoursTo||"08:00"}`}/>}<Rule icon={PartyPopper} title="Вечірки та заходи:" value={getRuleLabel(housing.partiesRule)}/>{housing.additionalRules&&<Rule icon={ShieldCheck} title="Додатково:" value={housing.additionalRules}/>}</div></section>
    {safety.length>0&&<section className="border-b border-[#D8DDE0] py-7"><Title>Заходи безпеки</Title><div className="mt-4 space-y-2">{safety.map(x=>{const Icon=x.icon;return <div key={x.title} className="rounded-[7px] border border-[#7894A7] p-4"><div className="flex items-center gap-2 text-[14px] font-semibold text-[#202A31]"><Icon size={17} strokeWidth={1.6}/>{x.title}</div><p className="mt-2 text-[13px] leading-[1.45] text-[#414B52]">{x.description}</p></div>;})}</div></section>}
    <section className="py-7"><div className="grid max-w-[670px] gap-5 md:grid-cols-[250px_minmax(0,1fr)]"><div className="rounded-[8px] border border-[#BAC6CD] p-5"><div className="flex items-center gap-4"><div className="flex h-[72px] w-[72px] items-center justify-center rounded-full bg-[#EEF2F4]"><UserRound size={47} strokeWidth={1.2} className="text-[#8B969D]"/></div><div><p className="text-[16px] font-semibold">{housing.ownerName||"Господар"}</p><p className="mt-1 text-[12px] text-[#56636C]">Господар WayGo</p></div></div><div className="mt-4 border-t border-[#D8DDE0] pt-3"><div className="flex items-center justify-between text-[12px]"><span>Відгуки</span><strong>{reviewCount}</strong></div><div className="mt-2 flex items-center justify-between text-[12px]"><span>Рейтинг</span><strong>{averageRating>0?averageRating.toFixed(2):"—"}</strong></div></div></div><div className="flex flex-col justify-center"><p className="text-[13px] leading-[1.5] text-[#252E34]">Зв’яжіться з господарем через WayGo, якщо у вас є запитання щодо помешкання чи майбутнього бронювання.</p><button type="button" className="mt-5 h-[42px] rounded-[6px] border border-[#AEBAC2] text-[14px] font-medium text-[#4C5961] hover:border-[#355872] hover:text-[#355872]">Написати господарю</button></div></div><p className="mt-5 flex max-w-[670px] items-start gap-2 text-[10px] leading-[1.4] text-[#56636C]"><ShieldCheck size={14} className="mt-[1px] shrink-0"/>Щоб захистити свої платіжні та персональні дані, здійснюйте оплату та спілкуйтеся з господарем виключно через платформу WayGo.</p></section>
  </div>;
};
const Title=({children}:{children:React.ReactNode})=><h2 className="text-[18px] font-semibold text-[#111820]">{children}</h2>;
const Rule=({icon:Icon,title,value}:{icon:typeof Clock3;title:string;value:string})=><div className="grid grid-cols-[20px_190px_minmax(0,1fr)] items-start gap-2 text-[13px]"><Icon size={17} strokeWidth={1.5} className="mt-[1px]"/><span className="font-semibold text-[#202A31]">{title}</span><span className="text-[#414B52]">{value}</span></div>;
const RatingMetric=({label,value}:RatingMetricItem)=>{const v=Math.min(Math.max(value,0),5);return <div><div className="flex items-center justify-between text-[11px] text-[#414B52]"><span>{label}</span><span className="font-medium">{v.toFixed(1)}</span></div><div className="mt-1 h-[4px] overflow-hidden rounded-full bg-[#D8DDE0]"><div className="h-full rounded-full bg-[#243C4E]" style={{width:`${v/5*100}%`}}/></div></div>;};
export default HousingDetailsContent;
